---
- hosts: localhost
  become: yes
  tasks:
  - name: updating ubuntu packages
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: installing openjdk-8
    package: 
      name: openjdk-8-jdk
      state: present
  - name: removeing env file
    file:
      path: /etc/environment
      state: absent
  - name: setting environmental variables
    template:
      src: ./environment.j2
      dest: /etc/environment
  - name: "refresh environment"
    shell: source /etc/environment
    args:
      executable: /bin/bash
  - name: installing maven package
    package:
      name: maven
      state: present
  - name: "creating a shopizer folder"
    file:
      path: /opt/shopizer
      state: directory
  - name: "downloading shopizer from git"
    git:
      repo: 'git://github.com/shopizer-ecommerce/shopizer.git'
      dest: ~/shopizer/
  - name: chaning floder 
    shell: cd ~/shopizer/
  #- name: moving shopizer into /opt/
  #  shell : mv ./shopizer /opt/ 
  - name: building the application
    shell: mvn clean install
  - name: changing directory
    command: cd sm-shop/
    
  #- name: Run the application from Spring boot
  #  command: mvn spring-boot:run
  #  args:
  #    chdir: sm-shop/
  #    executable: /bin/bash

  #- name: change directory to sm-shop
  #  shell: cd sm-shop
  #  args:
  #    executable: /bin/bash
  - name: Run the application from Spring boot
    shell: mvn spring-boot:run
    args:
      executable: /bin/bash
  
  

    
    
      